# Generated by Django 5.2.7 on 2025-10-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoreboard', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_home', models.IntegerField(default=0)),
                ('pass_away', models.IntegerField(default=0)),
                ('shoot_home', models.IntegerField(default=0)),
                ('shoot_away', models.IntegerField(default=0)),
                ('on_target_home', models.IntegerField(default=0)),
                ('on_target_away', models.IntegerField(default=0)),
                ('ball_possession_home', models.FloatField(default=0)),
                ('ball_possession_away', models.FloatField(default=0)),
                ('red_card_home', models.IntegerField(default=0)),
                ('red_card_away', models.IntegerField(default=0)),
                ('yellow_card_home', models.IntegerField(default=0)),
                ('yellow_card_away', models.IntegerField(default=0)),
                ('offside_home', models.IntegerField(default=0)),
                ('offside_away', models.IntegerField(default=0)),
                ('corner_home', models.IntegerField(default=0)),
                ('corner_away', models.IntegerField(default=0)),
                ('team_home', models.CharField(default='Team Home', max_length=100)),
                ('team_away', models.CharField(default='Team Away', max_length=100)),
                ('score_home', models.IntegerField(default=0)),
                ('score_away', models.IntegerField(default=0)),
                ('stadium', models.CharField(default='Stadium', max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match')),
            ],
        ),
    ]
