# Generated by Django 5.2.5 on 2025-10-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_alter_match_round'),
        ('statistik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistik',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
    ]
