# Generated by Django 5.2.5 on 2025-10-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistik', '0002_alter_statistik_match_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistik',
            old_name='match_id',
            new_name='match',
        ),
    ]
