# Generated by Django 5.2.7 on 2025-10-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoreboard', '0002_alter_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='YouTube or stream embed link')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='scoreboard.match')),
            ],
        ),
    ]
