# Generated by Django 5.2.7 on 2025-10-21 12:03

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='video_url',
        ),
        migrations.AddField(
            model_name='highlight',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='YouTube, Vimeo, or other embed link', null=True),
        ),
    ]
