# Generated by Django 5.2.7 on 2025-10-22 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=100)),
                ('home_team_code', models.CharField(choices=[('jp', 'Japan'), ('ir', 'Iran'), ('kr', 'South Korea'), ('au', 'Australia'), ('sa', 'Saudi Arabia'), ('uz', 'Uzbekistan'), ('jo', 'Jordan'), ('iq', 'Iraq'), ('ae', 'United Arab Emirates'), ('qa', 'Qatar'), ('cn', 'China'), ('om', 'Oman'), ('id', 'Indonesia'), ('bh', 'Bahrain'), ('kw', 'Kuwait'), ('th', 'Thailand'), ('kp', 'North Korea'), ('ps', 'Palestine'), ('sy', 'Syria'), ('vn', 'Vietnam'), ('my', 'Malaysia'), ('lb', 'Lebanon'), ('np', 'Nepal'), ('bd', 'Bangladesh'), ('mm', 'Myanmar'), ('mv', 'Maldives'), ('af', 'Afghanistan'), ('ph', 'Philippines'), ('hk', 'Hong Kong'), ('tm', 'Turkmenistan'), ('kg', 'Kyrgyzstan'), ('tj', 'Tajikistan'), ('tw', 'Chinese Taipei'), ('ye', 'Yemen'), ('bn', 'Brunei'), ('la', 'Laos'), ('lk', 'Sri Lanka'), ('kh', 'Cambodia'), ('bt', 'Bhutan'), ('gu', 'Guam'), ('mn', 'Mongolia'), ('pk', 'Pakistan'), ('tl', 'Timor-Leste'), ('mo', 'Macau'), ('sg', 'Singapore'), ('in', 'India')], default='', max_length=3)),
                ('away_team', models.CharField(max_length=100)),
                ('away_team_code', models.CharField(choices=[('jp', 'Japan'), ('ir', 'Iran'), ('kr', 'South Korea'), ('au', 'Australia'), ('sa', 'Saudi Arabia'), ('uz', 'Uzbekistan'), ('jo', 'Jordan'), ('iq', 'Iraq'), ('ae', 'United Arab Emirates'), ('qa', 'Qatar'), ('cn', 'China'), ('om', 'Oman'), ('id', 'Indonesia'), ('bh', 'Bahrain'), ('kw', 'Kuwait'), ('th', 'Thailand'), ('kp', 'North Korea'), ('ps', 'Palestine'), ('sy', 'Syria'), ('vn', 'Vietnam'), ('my', 'Malaysia'), ('lb', 'Lebanon'), ('np', 'Nepal'), ('bd', 'Bangladesh'), ('mm', 'Myanmar'), ('mv', 'Maldives'), ('af', 'Afghanistan'), ('ph', 'Philippines'), ('hk', 'Hong Kong'), ('tm', 'Turkmenistan'), ('kg', 'Kyrgyzstan'), ('tj', 'Tajikistan'), ('tw', 'Chinese Taipei'), ('ye', 'Yemen'), ('bn', 'Brunei'), ('la', 'Laos'), ('lk', 'Sri Lanka'), ('kh', 'Cambodia'), ('bt', 'Bhutan'), ('gu', 'Guam'), ('mn', 'Mongolia'), ('pk', 'Pakistan'), ('tl', 'Timor-Leste'), ('mo', 'Macau'), ('sg', 'Singapore'), ('in', 'India')], default='', max_length=3)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('match_date', models.DateTimeField()),
                ('stadium', models.CharField(max_length=100)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], default='upcoming', max_length=10)),
            ],
        ),
    ]
