# Generated by Django 5.2.7 on 2025-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_code',
            field=models.CharField(choices=[('jp', 'Japan'), ('ir', 'Iran'), ('kr', 'South Korea'), ('au', 'Australia'), ('sa', 'Saudi Arabia'), ('uz', 'Uzbekistan'), ('jo', 'Jordan'), ('iq', 'Iraq'), ('ae', 'United Arab Emirates'), ('qa', 'Qatar'), ('cn', 'China'), ('om', 'Oman'), ('id', 'Indonesia'), ('bh', 'Bahrain'), ('kw', 'Kuwait'), ('th', 'Thailand'), ('kp', 'North Korea'), ('ps', 'Palestine'), ('sy', 'Syria'), ('vn', 'Vietnam'), ('my', 'Malaysia'), ('lb', 'Lebanon'), ('np', 'Nepal'), ('bd', 'Bangladesh'), ('mm', 'Myanmar'), ('mv', 'Maldives'), ('af', 'Afghanistan'), ('ph', 'Philippines'), ('hk', 'Hong Kong'), ('tm', 'Turkmenistan'), ('kg', 'Kyrgyzstan'), ('tj', 'Tajikistan'), ('tw', 'Chinese Taipei'), ('ye', 'Yemen'), ('bn', 'Brunei'), ('la', 'Laos'), ('lk', 'Sri Lanka'), ('kh', 'Cambodia'), ('bt', 'Bhutan'), ('gu', 'Guam'), ('mn', 'Mongolia'), ('pk', 'Pakistan'), ('tl', 'Timor-Leste'), ('mo', 'Macau'), ('sg', 'Singapore'), ('in', 'India')], max_length=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_code',
            field=models.CharField(choices=[('jp', 'Japan'), ('ir', 'Iran'), ('kr', 'South Korea'), ('au', 'Australia'), ('sa', 'Saudi Arabia'), ('uz', 'Uzbekistan'), ('jo', 'Jordan'), ('iq', 'Iraq'), ('ae', 'United Arab Emirates'), ('qa', 'Qatar'), ('cn', 'China'), ('om', 'Oman'), ('id', 'Indonesia'), ('bh', 'Bahrain'), ('kw', 'Kuwait'), ('th', 'Thailand'), ('kp', 'North Korea'), ('ps', 'Palestine'), ('sy', 'Syria'), ('vn', 'Vietnam'), ('my', 'Malaysia'), ('lb', 'Lebanon'), ('np', 'Nepal'), ('bd', 'Bangladesh'), ('mm', 'Myanmar'), ('mv', 'Maldives'), ('af', 'Afghanistan'), ('ph', 'Philippines'), ('hk', 'Hong Kong'), ('tm', 'Turkmenistan'), ('kg', 'Kyrgyzstan'), ('tj', 'Tajikistan'), ('tw', 'Chinese Taipei'), ('ye', 'Yemen'), ('bn', 'Brunei'), ('la', 'Laos'), ('lk', 'Sri Lanka'), ('kh', 'Cambodia'), ('bt', 'Bhutan'), ('gu', 'Guam'), ('mn', 'Mongolia'), ('pk', 'Pakistan'), ('tl', 'Timor-Leste'), ('mo', 'Macau'), ('sg', 'Singapore'), ('in', 'India')], max_length=3),
        ),
    ]
