# Generated by Django 5.2.5 on 2025-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_alter_match_id_alter_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
