# Generated by Django 5.2.7 on 2025-10-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_alter_match_id'),
        ('scoreboard', '0003_match_group_match_round'),
    ]

    operations = [
    ]
