# Generated by Django 5.2.5 on 2025-10-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_alter_match_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
