# Generated by Django 5.2.7 on 2025-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_alter_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
