# Generated by Django 5.2.7 on 2025-10-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_merge_20251021_1100'),
        ('scoreboard', '0009_alter_match_round'),
    ]

    operations = [
    ]
