# Generated by Django 5.2.5 on 2025-10-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_merge_20251021_1100'),
        ('scoreboard', '0010_alter_match_away_team_code_and_more'),
    ]

    operations = [
    ]
