# Generated by Django 5.2.7 on 2025-10-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0010_merge_0004_merge_20251021_1100_0009_alter_match_round'),
        ('scoreboard', '0011_merge_20251022_2146'),
    ]

    operations = [
    ]
