<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-21 10:51
=======
# Generated by Django 5.2.7 on 2025-10-23 17:50
>>>>>>> 977c363b480a5947e4eea9b51222e2fd4283c8f0

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('scoreboard', '0003_match_group_match_round'),
=======
        ('scoreboard', '0001_initial'),
>>>>>>> 977c363b480a5947e4eea9b51222e2fd4283c8f0
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
>>>>>>> 977c363b480a5947e4eea9b51222e2fd4283c8f0
            ],
        ),
    ]
