# Generated by Django 5.2.7 on 2025-10-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('jp', 'Japan'), ('ir', 'Iran'), ('kr', 'South Korea'), ('au', 'Australia'), ('sa', 'Saudi Arabia'), ('uz', 'Uzbekistan'), ('jo', 'Jordan'), ('iq', 'Iraq'), ('ae', 'United Arab Emirates'), ('qa', 'Qatar'), ('cn', 'China'), ('om', 'Oman'), ('id', 'Indonesia'), ('bh', 'Bahrain'), ('kw', 'Kuwait'), ('th', 'Thailand'), ('kp', 'North Korea'), ('ps', 'Palestine'), ('sy', 'Syria'), ('vn', 'Vietnam'), ('my', 'Malaysia'), ('lb', 'Lebanon'), ('np', 'Nepal'), ('bd', 'Bangladesh'), ('mm', 'Myanmar'), ('mv', 'Maldives'), ('af', 'Afghanistan'), ('ph', 'Philippines'), ('hk', 'Hong Kong'), ('tm', 'Turkmenistan'), ('kg', 'Kyrgyzstan'), ('tj', 'Tajikistan'), ('tw', 'Chinese Taipei'), ('ye', 'Yemen'), ('bn', 'Brunei'), ('la', 'Laos'), ('lk', 'Sri Lanka'), ('kh', 'Cambodia'), ('bt', 'Bhutan'), ('gu', 'Guam'), ('mn', 'Mongolia'), ('pk', 'Pakistan'), ('tl', 'Timor-Leste'), ('mo', 'Macau'), ('sg', 'Singapore'), ('in', 'India')], max_length=3, unique=True)),
                ('name', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('asal', models.CharField(max_length=100)),
                ('umur', models.PositiveIntegerField()),
                ('nomor', models.PositiveIntegerField()),
                ('tim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lineup.team')),
            ],
            options={
                'ordering': ['nomor'],
                'unique_together': {('nomor', 'tim')},
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='scoreboard.match')),
                ('players', models.ManyToManyField(related_name='lineups', to='lineup.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup.team')),
            ],
            options={
                'unique_together': {('match', 'team')},
            },
        ),
    ]
